spring:
  application:
    name: simpleui

  ai:
    openai:
      embedding:
        enabled: false
      image:
        enabled: false

    mcp:
      client:
        enabled: true
        toolcallback:
          enabled: false
        type: SYNC

server:
  port: 9091
