spring:
  application:
    name: simpleui

  ai:
    openai:
      embedding:
        enabled: false
      image:
        enabled: false
      transcription:
        enabled: false
    mcp:
      client:
        enabled: true
        type: SYNC
