spring:
  application:
    name: simpleui

  ai:
    openai:
      embedding:
        enabled: false
      image:
        enabled: false

    mcp:
      client:
        enabled: true
        type: SYNC
