name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Check Spotless
      run: mvn -B spotless:check
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      env:
        VCAP_SERVICES: |
          {
            "genai":[
              { 
                "name":"genai",
                "label":"genai",
                "credentials":{
                  "endpoint":{
                    "api_base":"http://localhost:1234/test",
                    "name":"test",
                    "api_key":"xxx",
                    "config_url":"http://localhost:1234/test/config/v1/endpoint",
                    "dashboard_url":"http://localhost:1234/ui/endpoint/test"
                  }
                }
              }
            ]
          }
